# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11zu6s27ucw2erpPDnNS9DqvjxZCFf_E9
"""

#importation de la bibliotheque pandas
import pandas as pd
data = {'Nom' : ['John', 'Mary', 'Bob', 'Sarah', 'Tom', 'Lisa'],
        'Département' : ['IT', 'Marketing', 'Sales', 'IT', 'Finance', 'Marketing'],
        'Âge' : [30, 40, 25, 35, 45, 28],
        'Sexe' : ['Homme', 'Femme', 'Homme', 'Femme ', 'Homme', 'Femme'],
        'Salaire' : [50000, 60000, 45000, 55000, 70000, 55000],
        'Expérience' : [3, 7, 2, 5, 10, 4]}

#Création du dataframe "employe_df"
employe_df = pd.DataFrame (data)
print(employe_df)

#la méthode iloc pour sélectionner les 3 premières lignes de la trame de données.
c=employe_df.iloc[0:3,:]
print("1.les 3 premières lignes de la trame de données sont:")
print(c)

#la méthode loc pour sélectionner toutes les lignes où le département est « Marketing »
d= employe_df.loc[employe_df['Département'] == 'Marketing', ['Nom', 'Département', 'Âge', 'Sexe', 'Salaire', 'Expérience']]
print("2.les lignes où le département est « Marketing » sont:")
print(d)

#la méthode iloc pour sélectionner les colonnes Âge et Sexe pour les 4 premières lignes du dataframe.
e=employe_df.iloc[0:4,2:4]
print("3.les colonnes Âge et Sexe pour les 4 premières lignes du dataframe sont:")
print(e)

#la méthode loc pour sélectionner les colonnes Salaire et Expérience pour toutes les lignes où le sexe est « Homme ».
f=employe_df.loc[employe_df['Sexe']=='Homme',['Salaire','Expérience']]
print("4.les colonnes Salaire et Expérience pour toutes les lignes où le sexe est « Homme » sont:")
print(f)